In [1]:
import pandas as pd
%load_ext autoreload
%autoreload 2
DATA_FP = r"C:\Users\micha\OneDrive\Documents\data\lstm_data.csv"


In [2]:
import lstm
from lstm import PortfolioDataset, HybridPortfolioModel, PortfolioOptimizer



In [3]:
benchmark_weights = {
    'Materials': 0.025,
    'Industrials': 0.10,
    'Consumer Discretionary': 0.10,
    'Consumer Staples': 0.05,
    'Health Care': 0.10,
    'Financials': 0.15,
    'Info Tech': 0.30,
    'Comm Services': 0.10,
    'Utilities': 0.025,
    'Real Estate': 0.025,
    'Energy': 0.025
}

# Portfolio Dataset

In [4]:
pfd = PortfolioDataset(data_path=DATA_FP, window_size=252, portfolio_columns=lstm.sp500_sectors.values())

In [33]:
pfd.data.head()

SPX  Info Tech  Financials  Consumer Discretionary  \
2016-09-19 -0.000019  -0.002402    0.004907               -0.001058   
2016-09-20  0.000299  -0.000177    0.000935                0.000969   
2016-09-21  0.010858   0.010877    0.006613                0.009018   
2016-09-22  0.006479   0.005519    0.002750                0.007700   
2016-09-23 -0.005753  -0.009660   -0.006967               -0.002271   

            Health Care  Comm Services  Industrials  Consumer Staples  \
2016-09-19    -0.004143      -0.006857     0.003397         -0.001458   
2016-09-20     0.003844      -0.001841     0.001299          0.002398   
2016-09-21     0.009972       0.012755     0.012795          0.005566   
2016-09-22     0.007544       0.011261     0.007142          0.008882   
2016-09-23    -0.003457       0.003706    -0.006502         -0.005061   

              Energy  Utilities  ...  S5RLST Index_1bf_eps_pct_chg_3m  \
2016-09-19 -0.001208   0.009898  ...                           4.8429   
2016-09-20 -0.008277  -0.001940  ...                           4.8052   
2016-09-21  0.020973   0.020788  ...                           4.8018   
2016-09-22  0.002167   0.005651  ...                           4.8018   
2016-09-23 -0.012689  -0.001275  ...                           4.7896   

            S5RLST Index_1bf_eps_pct_chg_6m  S5RLST Index_1bf_eps_pct_chg_12m  \
2016-09-19                           4.8429                            4.8429   
2016-09-20                           4.8052                            4.8052   
2016-09-21                           4.8018                            4.8018   
2016-09-22                           4.8018                            4.8018   
2016-09-23                           4.7896                            4.7896   

            S5RLST Index1bf_eps_zscore_3m  S5RLST Index_trend_1m  \
2016-09-19                       7.811266               0.230614   
2016-09-20                       5.456522               0.459433   
2016-09-21                       4.422120               0.688090   
2016-09-22                       3.800540               0.916748   
2016-09-23                       3.364470               1.144824   

            S5RLST Index_1bf_eps_rsi_21d  S5RLST Index_1bf_eps_rsi_63d  \
2016-09-19                    100.000000                    100.000000   
2016-09-20                     99.866946                     99.866946   
2016-09-21                     99.854886                     99.854886   
2016-09-22                     99.854886                     99.854886   
2016-09-23                     99.811610                     99.811610   

            S5RLST Index_1bf_eps_rsi_126d  S5RLST Index_1bf_eps_rsi_cross  \
2016-09-19                     100.000000                             0.0   
2016-09-20                      99.866946                             0.0   
2016-09-21                      99.854886                             0.0   
2016-09-22                      99.854886                             0.0   
2016-09-23                      99.811610                             0.0   

            S5RLST Index_1bf_eps_rsi_extreme  
2016-09-19                               1.0  
2016-09-20                               1.0  
2016-09-21                               1.0  
2016-09-22                               1.0  
2016-09-23                               1.0  

[5 rows x 207 columns]

In [5]:
features, returns = pfd.prepare_sequence(start_idx=0)

In [6]:
features

tensor([[-2.4017e-03,  4.9068e-03, -1.0585e-03,  ...,  1.0000e+02,
          0.0000e+00,  1.0000e+00],
        [-1.7720e-04,  9.3487e-04,  9.6888e-04,  ...,  9.9867e+01,
          0.0000e+00,  1.0000e+00],
        [ 1.0877e-02,  6.6126e-03,  9.0177e-03,  ...,  9.9855e+01,
          0.0000e+00,  1.0000e+00],
        ...,
        [-3.7286e-03, -3.4829e-03, -5.4594e-03,  ...,  5.5256e+01,
         -1.0673e+01,  1.0000e+00],
        [ 2.9899e-03,  4.7464e-03, -2.3164e-03,  ...,  5.5239e+01,
         -9.9663e+00,  1.0000e+00],
        [-3.2520e-04,  1.0099e-02, -4.2530e-03,  ...,  5.1846e+01,
         -1.1721e+01,  1.0000e+00]])

In [7]:
returns

tensor([ 0.0594,  0.1146,  0.2675, -0.0149,  0.1302,  0.1257,  0.2444, -0.0214,
        -0.0249,  0.0141,  0.1168])

In [8]:
features, returns = pfd.get_prediction_data()

In [9]:
features

tensor([[ 4.3534e-03, -5.3826e-03,  1.1696e-02,  ...,  2.3521e+01,
         -2.4019e+00,  1.0000e+00],
        [ 3.8291e-03,  1.5572e-03,  1.1573e-02,  ...,  2.1706e+01,
         -1.7956e+00,  1.0000e+00],
        [-1.7688e-02, -1.0753e-02, -2.1879e-02,  ...,  2.1364e+01,
         -2.8435e+00,  1.0000e+00],
        ...,
        [-7.7662e-03,  4.1505e-03, -2.7632e-03,  ...,  4.2046e+01,
          2.8241e+00,  0.0000e+00],
        [-1.5710e-02, -1.2861e-02, -1.9796e-02,  ...,  4.1883e+01,
          5.5956e-01,  0.0000e+00],
        [ 1.0894e-02,  9.5727e-03,  1.0163e-02,  ...,  4.1267e+01,
          3.2736e+00,  0.0000e+00]])

In [10]:
returns

tensor([0.0887, 0.1619, 0.2497, 0.1537, 0.0022, 0.2886, 0.2420, 0.2892, 0.2810,
        0.1102, 0.0862])

# Hybrid Portfolio Model

In [11]:
hpm =  HybridPortfolioModel(pfd.state_size, 64, pfd.num_assets, benchmark_weights=benchmark_weights)

In [12]:
hpm.hidden_dim

64

In [13]:
hpm.num_layers

2

In [14]:
hpm.lstm

LSTM(182, 64, num_layers=2, batch_first=True, dropout=0.2)

In [15]:
hpm.allocation

Sequential(
  (0): Linear(in_features=64, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=11, bias=True)
  (3): Softmax(dim=-1)
  (4): MinMaxScaler()
)

In [16]:
hpm.forward(pfd.prepare_sequence(850)[0].unsqueeze(0))

tensor([[0.0792, 0.0792, 0.0792, 0.0792, 0.0693, 0.0891, 0.2000, 0.0891, 0.0891,
         0.0792, 0.0693]], grad_fn=<MinimumBackward0>)

# Portfolio Optimizer

In [17]:
optimizer = PortfolioOptimizer(pfd, hidden_dim=64, lr=0.0005)


In [28]:
features, returns = pfd.prepare_sequence(-1)


In [29]:
returns

tensor([ 0.0535,  0.1158,  0.2667, -0.0162,  0.1234,  0.1162,  0.2492,  0.0145,
        -0.0056,  0.0128,  0.1168])

In [ ]:
loss, weights = optimizer.train_step(features, returns)

In [20]:
weights

tensor([0.0784, 0.0784, 0.0784, 0.0980, 0.0784, 0.0784, 0.2000, 0.0882, 0.0784,
        0.0784, 0.0686])

In [24]:
weights = hpm(features.unsqueeze(0))
weights

tensor([[0.0707, 0.0808, 0.0808, 0.0808, 0.0707, 0.0909, 0.2020, 0.0909, 0.0909,
         0.0707, 0.0707]], grad_fn=<MinimumBackward0>)

In [30]:
loss = -optimizer.calculate_sharpe(weights.squeeze(), returns)


In [31]:
loss

tensor(0.0281, dtype=torch.float64, grad_fn=<NegBackward0>)